@startsalt
{+
{/ Start
<b>Type
Condition
Finish } |
{
  [<b>If          ] | [ <&circle-x> ]
  [Do          ] | *
  [While       ] | *
  [For         ] | *
  [For Each    ] | [ <&action-undo> ]
}
}
@endsalt