@startsalt
{+
{/ Start
Type
Condition
<b>Finish } |
{
  [<b>==         ] | [ <&circle-x> ]
  [!=         ] | *
  [>          ] | *
  [>=         ] | *
  [<          ] | *
  [<=         ] | [ <&action-undo> ]
}
}
@endsalt