@startsalt
{+
{/ Start
<b>Type
Identifier
Value
Finish } |
{
  [Modify      ] | [ <&circle-x> ]
  [Boolean     ] | *
  [<b>Integer     ] | *
  [Double      ] | *
  [Character   ] | [ <&action-undo> ]
}
}
@endsalt