@startsalt
{+
{/ Start
Type
Condition
<b>Finish } |
{
  [<b>Equal         ] | [ <&circle-x> ]
  [Not Equal     ] | *
  [Greater Than  ] | *
  [Greater Or Eq ] | *
  [Less Than     ] | *
  [Less Or Eq    ] | [ <&action-undo> ]
}
}
@endsalt